[project]
name = "receipt-management-api"
version = "0.1.0"
description = "REST API for receipt management"
authors = [
    {name = "Yuriy"},
]
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.104.1",
    "uvicorn[standard]>=0.24.0",
]
